### ISSUE TITLE
Invalid Target: (dynamics)

### ISSUE THREAD

**Issue by YauheniTalochkaN** [NVIDIA/cuda-quantum#2914]
### Required prerequisites

- [x] Consult the [security policy](https://github.com/NVIDIA/cuda-quantum/security/policy). If reporting a security vulnerability, do not report the bug using this form. Use the process described in the policy to report the issue.
- [x] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [x] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [ ] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

Dear developers,

Could you please help me resolve the following issue with compiling the [heisenberg_model](https://github.com/NVIDIA/cuda-quantum/blob/releases/v0.11.0/docs/sphinx/examples/cpp/dynamics/heisenberg_model.cpp) example? 

When using the command: 
`
nvq++ --target dynamics heisenberg_model.cpp -o heisenberg_model.x 
`

I encounter the error: 
`
nvq++:646: Invalid Target: (dynamics) 
`

CUDA-Q version 0.11.0 was installed from [
install_cuda_quantum_cu12.x86_64 ](https://github.com/NVIDIA/cuda-quantum/releases/tag/0.11.0).

### Steps to reproduce the bug

`
nvq++ --target dynamics heisenberg_model.cpp -o heisenberg_model.x 
`

### Expected behavior

Successful compilation of heisenberg_model.cpp without the "Invalid Target: (dynamics)" error.

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA-Q version**: 0.11.0
- **C++ compiler**: gcc 14.2.1 & nvq++ 0.11.0
- **Operating system**: Fedora 41

**Comment by bebora** [comment]
I can confirm this occurs when using the pre-built binaries. The container image is not affected. If you compare `nvq++ --list-targets` between the release on Github and the corresponding container (nvcr.io/nvidia/nightly/cuda-quantum:cu12-0.11.0), dynamics is the only target missing.

**Comment by bebora** [comment]
Hi @YauheniTalochkaN, I am a CUDA-Q user and I am not affiliated with NVIDIA. We will have to wait for feedback from the maintainers. New releases are typically published every few months. I suggest using the container version in the meantime if you need the dynamics target.

**Comment by YauheniTalochkaN** [comment]
Thank you a lot!

**Comment by bettinaheim** [comment]
After looking into it: There are two issues with the installer. I'll share the workaround here, and we will update the binaries of the release shortly. Issue 1 is that the dynamics.yml configuration is missing, issue 2 is that an rpath is missing in the built binary. 

Workaround: 
- install the released version and its dependencies (C development headers and CUDA runtime libraries) following the instructions in our [installation guide](https://nvidia.github.io/cuda-quantum/latest/using/install/local_installation.html#cuda-dependencies-prebuilt-binaries) 
- after installation, the environment variable `$CUDAQ_INSTALL_PATH` should be defined; create the file `$CUDAQ_INSTALL_PATH/targets/dynamics.yml` with the following content:
```
# ============================================================================ #
# Copyright (c) 2022 - 2025 NVIDIA Corporation & Affiliates.                   #
# All rights reserved.                                                         #
#                                                                              #
# This source code and the accompanying materials are made available under     #
# the terms of the Apache License 2.0 which accompanies this distribution.     #
# ============================================================================ #

name: dynamics
description: "Dynamics simulation backend"
gpu-requirements: true
config:
  nvqir-simulation-backend: dynamics
  platform-library: mqpu
  preprocessor-defines: ["-D CUDAQ_ANALOG_TARGET"]
  library-mode: true
```
- finally, add the cutensor library path to you LD_LIBRARY_PATH: `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cutensor/lib`

With these two fixes, you should be able to compile and run the examples while we work on a published fix.
